---
chapter:
  word: Chapitre
  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
section: Section
table: Tableau
figure: Figure
fig: Fig
aside: Encadré
listing: Listing
equation: Équation
eq: Éq
frontmatter: Introduction
contents: Table des matières
